---
title: "Data Literacy with R for Students of Humanities - ATRIUM summer school"
output: html
embed-resources: true
markdown: asciidoc
---

**REGISTRATION CLOSED**

## Venue and date

Charles University, Prague, August 4 - 15, 2025

Faculty of Mathematics and Physics, School of Computer Science

Malostranské náměstí 25, 4th floor, Room S1

This course in the course catalog: <https://is.cuni.cz/studium/eng/predmety/index.php?do=predmet&kod=NPFL146>

## Self-study assignments

Courtesy of <https://www.datacamp.com/>. The links in this schedule always point to the first lecture in the given chapter, but you are expected to complete the entire chapter. This web can easily get outdated. Please follow your assignments directly on DataCamp.

## Schedule

### Monday, August 4

+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| time slot     | contents                                                                                                                                                                 |
+===============+==========================================================================================================================================================================+
| 9:00 - 10:30  | 🧭 [01_Introduction](https://ufal.github.io/R_BEGINNERS_SHORT/01_Introduction.html).- 🧭[02_HowToRStudio](https://ufal.github.io/R_BEGINNERS_SHORT/02_HowToRStudio.html) |
|               |                                                                                                                                                                          |
|               | 🏋️Follow with 02 and log in at RStudio. \|                                                                                                                               |
|               |                                                                                                                                                                          |
|               | ❗Create your account at [DataCamp](%5Bhttps://www.datacamp.com/users/sign_up%5D(#0)) with the same e-mail address you registered with to this course.                   |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:50 - 12:10 | 🏋️ Explore RStudio with [Exercise T_01_01_01_YourFirstQuartoDoc](https://ufal.github.io/R_BEGINNERS_SHORT/EXERCISES/T_01_01_01_YourFirstQuartoDoc.html) \|               |
|               |                                                                                                                                                                          |
|               | 🧭[03_RStudioFileManagement](https://ufal.github.io/R_BEGINNERS_SHORT/03_RStudioFileManagement.html)                                                                     |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14:00 - 15:30 | 🧭 [04_NavigatingRStudioForProgramming](https://ufal.github.io/R_BEGINNERS_SHORT/04_NavigatingRStudioForProgramming.html)                                                |
|               |                                                                                                                                                                          |
|               | 🧭[05_VariablesFunctions](https://ufal.github.io/R_BEGINNERS_SHORT/05_VariablesFunctions.html)                                                                           |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15:50 - 17:10 | 🏋️🎧DataCamp \|                                                                                                                                                          |
|               |                                                                                                                                                                          |
|               | <https://campus.datacamp.com/courses/free-introduction-to-r/chapter-1-intro-to-basics-1>                                                                                 |
|               |                                                                                                                                                                          |
|               | <https://campus.datacamp.com/courses/free-introduction-to-r/chapter-2-vectors-2>                                                                                         |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

#### Tuesday, August 5

+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| time slot     | contents                                                                                                                                                                                                                                                                                    |      |
+===============+=============================================================================================================================================================================================================================================================================================+======+
| 9:00 - 10:30  | 🧭 🏋️[06_WorkingDirectory](https://ufal.github.io/R_BEGINNERS_SHORT/06_WorkingDirectory.html) \|                                                                                                                                                                                            |      |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| 10:50 - 12:10 | 🏋️ ️[T_02_01_01](https://ufal.github.io/R_BEGINNERS_SHORT/EXERCISES/T_02_01_01.html)   \|                                                                                                                                                                                                    |      |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| 14:00 - 15:30 | 🧭 [07_Exploring_dataframes](https://ufal.github.io/R_BEGINNERS_SHORT/07_Exploring_dataframes.html)                                                                                                                                                                                         |      |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| 15:50 - 17:10 | 🏋️🎧DataCamp <https://campus.datacamp.com/courses/introduction-to-the-tidyverse/data-visualization?ex=1> <https://campus.datacamp.com/courses/introduction-to-the-tidyverse/data-wrangling-1?ex=1> <https://campus.datacamp.com/courses/free-introduction-to-r/chapter-4-factors-4?ex=1> \| |      |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+

#### Wednesday, August 6

+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| time slot     | contents                                                                                                                                                                   |
+===============+============================================================================================================================================================================+
| 9:00 - 10:30  | 🏋️[T_04_01_001](https://ufal.github.io/R_BEGINNERS_SHORT/EXERCISES/T_04_01_001.html) 🧭 [08_DiversePlots](https://ufal.github.io/R_BEGINNERS_SHORT/08_DiversePlots.html)   |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:50 - 12:10 | 🏋️[T_03_01_01](https://ufal.github.io/R_BEGINNERS_SHORT/EXERCISES/T_03_01_01.html)                                                                                         |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14:00 - 15:30 | 🏋️🎧DataCamp <https://campus.datacamp.com/courses/introduction-to-data-visualization-with-ggplot2/introduction-713e9e31-9e6c-4a0f-b242-9bc4e692fd8a?ex=1>                  |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15:50 - 17:10 | 🏋️🎧DataCamp <https://campus.datacamp.com/courses/introduction-to-data-visualization-with-ggplot2/aesthetics?ex=1>                                                         |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

#### Thursday, August 7

+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| time slot     | contents                                                                                                                                                                                                   |
+===============+============================================================================================================================================================================================================+
| 9:00 - 10:30  | 🎪Discussion over T_03_01_01, live coding of solutions                                                                                                                                                     |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:50 - 12:10 | 🧭 [09_Aggregations_with_dplyr](https://ufal.github.io/R_BEGINNERS_SHORT/09_Aggregations_with_dplyr.html)                                                                                                  |
|               |                                                                                                                                                                                                            |
|               | [T_04_01_01](https://ufal.github.io/R_BEGINNERS_SHORT/EXERCISES/T_04_01_01.html)                                                                                                                           |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14:00 - 15:30 | 🏋️🎧DataCamp <https://campus.datacamp.com/courses/introduction-to-the-tidyverse/data-wrangling-1?ex=1> <https://campus.datacamp.com/courses/introduction-to-the-tidyverse/grouping-and-summarizing?ex=1>   |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15:50 - 17:10 | 🏋️🎧DataCamp <https://campus.datacamp.com/courses/data-manipulation-with-dplyr/selecting-and-transforming-data?ex=1>                                                                                       |
+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

#### Friday, August 8

+---------------+----------------------------------------------------------------------------------------------------------------------+
| time slot     | contents                                                                                                             |
+===============+======================================================================================================================+
| 9:00 - 10:30  | mutate and T_05_01_01 dplyr on billionaires                                                                          |
+---------------+----------------------------------------------------------------------------------------------------------------------+
| 10:50 - 12:10 | 🧭 [10_ggplot2OtherLayers](https://ufal.github.io/R_BEGINNERS_SHORT/10_ggplot2OtherLayers.html)                      |
+---------------+----------------------------------------------------------------------------------------------------------------------+
| 14:00 - 15:30 | 🏋️🎧Data Camp <https://campus.datacamp.com/courses/introduction-to-data-visualization-with-ggplot2/geometries?ex=1>  |
+---------------+----------------------------------------------------------------------------------------------------------------------+
| 15:50 - 17:10 | 🏋️🎧 <https://campus.datacamp.com/courses/introduction-to-data-visualization-with-ggplot2/themes?ex=1>               |
+---------------+----------------------------------------------------------------------------------------------------------------------+

#### Monday, August 11

+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| time slot     | contents                                                                                                                                                                                        |
+===============+=================================================================================================================================================================================================+
| 9:00 - 10:30  | 🧭[12_JoiningDplyr](https://ufal.github.io/R_BEGINNERS_SHORT/12_JoiningDplyr.html)                                                                                                              |
|               |                                                                                                                                                                                                 |
|               | 🏋️[T_06_01_02](https://ufal.github.io/R_BEGINNERS_SHORT/EXERCISES/T_06_01_02.html)                                                                                                              |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:50 - 12:10 | 🎪Finish the exercise. Discussion over the exercise, live solution coding                                                                                                                       |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14:00 - 15:30 | 🏋️🎧 DataCamp [https://campus.datacamp.com/courses/joining-data-with-dplyr/joining-tables-1?ex=1](#0) <https://campus.datacamp.com/courses/joining-data-with-dplyr/left-and-right-joins?ex=1>   |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15:50 - 17:10 | 🏋️🎧 DataCamp <https://campus.datacamp.com/courses/joining-data-with-dplyr/full-semi-and-anti-joins?ex=1>                                                                                       |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

#### Tuesday, August 12

+---------------+----------------------------------------------------------------------------------------------------------------------------------+
| time slot     | contents                                                                                                                         |
+===============+==================================================================================================================================+
| 9:00 - 10:30  | 🧭Data frames in base R. 🏋️🎧 DataCamp <https://campus.datacamp.com/courses/free-introduction-to-r/chapter-5-data-frames?ex=1>   |
+---------------+----------------------------------------------------------------------------------------------------------------------------------+
| 10:50 - 12:10 | 🏋️ Make sense of someone else's code (work in 3 - 4 groups)                                                                      |
+---------------+----------------------------------------------------------------------------------------------------------------------------------+
| 14:00 - 15:30 | 🎪Present the group results ("poster session")                                                                                   |
+---------------+----------------------------------------------------------------------------------------------------------------------------------+
| 15:50 - 17:10 | 🏋️🎧 DataCamp [https://campus.datacamp.com/courses/intermediate-r/chapter-1-conditionals-and-control-flow?ex=1](#0)              |
+---------------+----------------------------------------------------------------------------------------------------------------------------------+

#### Wednesday, August 13

+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| time slot     | contents                                                                                                                                               |
+===============+========================================================================================================================================================+
| 9:00 - 10:30  | 🧭Lists. 🧭For-loop. 🏋️🎧 DataCamp <https://campus.datacamp.com/courses/free-introduction-to-r/chapter-6-lists?ex=1>                                   |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10:50 - 12:10 | 🏋️🎧 DataCamp <https://campus.datacamp.com/courses/intermediate-r/chapter-2-loops?ex=1>                                                                |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14:00 - 15:30 | 🎪List file names in **a vector**, read each file, do something to it, and save it to a new file.                                                      |
|               |                                                                                                                                                        |
|               | 🧭Iteration with `purrr::map` .                                                                                                                        |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15:50 - 17:10 | 🏋️🎧 DataCamp <https://campus.datacamp.com/courses/foundations-of-functional-programming-with-purrr/simplifying-iteration-and-lists-with-purrr?ex=1>   |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+

#### Thursday, August 14

+---------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| time slot     | contents                                                                                                                                   |
+===============+============================================================================================================================================+
| 9:00 - 10:30  | `tidyr separate, unite, separate_longer_delim`                                                                                             |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| 10:50 - 12:10 | `tidyr pivot_longer, pivot_wider`                                                                                                          |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| 14:00 - 15:30 | 🏋️🎧 DataCamp <https://campus.datacamp.com/courses/reshaping-data-with-tidyr/tidy-data-1?ex=1>                                             |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| 15:50 - 17:10 | 🏋️🎧 DataCamp [https://campus.datacamp.com/courses/reshaping-data-with-tidyr/from-wide-to-long-and-back?ex=1](#0)                          |
|               |                                                                                                                                            |
|               | 🏋️🎧DataCamp <https://campus.datacamp.com/courses/intermediate-regular-expressions-in-r/regular-expressions-writing-custom-patterns?ex=1>  |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------+

#### Friday, August 15

+---------------+--------------------------------------------------------------------+
| time slot     | contents                                                           |
+===============+====================================================================+
| 9:00 - 10:30  | Write your own function. Source a file with your stored functions. |
+---------------+--------------------------------------------------------------------+
| 10:50 - 12:10 | Wrap-up.                                                           |
+---------------+--------------------------------------------------------------------+

## Recommended DataCamp courses

-   Complete those from which you did chapters in this course. Especially <https://campus.datacamp.com/courses/intermediate-r/chapter-3-functions?ex=1>.

-   [Categorical Data in the Tidyverse](https://campus.datacamp.com/courses/categorical-data-in-the-tidyverse/introduction-to-factor-variables?ex=1)

-   [Working with Dates and Times in R](https://campus.datacamp.com/courses/working-with-dates-and-times-in-r/dates-and-times-in-r?ex=11)

### Download a folder from this repository

It is easy to download this entire repository or one individual file directly from GitHub, but downloading a subfolder (e.g. `images_ATRIUM`) is tricky, because GitHub GUI does not enable it. Fortunately, there is a free third-party service for downloading folders from GitHub: <https://download-directory.github.io>. To download a folder from this repository, copy the URL below and replace `images_ATRIUM` with the name of the desired folder: <https://download-directory.github.io/?url=https://github.com/ufal/R_BEGINNERS_SHORT/tree/main/images_ATRIUM>.

### Additional resources

-   https://bookdown.org/yih_huynh/Guide-to-R-Book/ *R for Graduate Students* is extremely accessible.
