---
title: "Data Literacy with R for Students of Humanities"
echo: true
format:
  revealjs:
    toc: true
    slide-number: true
    notes: true
    pdf-export: true
    css: atrium.css
    chalkboard: true
    scrollable: false
    code-block-height: 650px
    echo: true
    output-location: slide
    preview-links: auto
  pdf:
    toc: true
    number-sections: true
    include-in-header: atrium.tex
  html:
    toc: true
    number-sections: true
---

## 
::: callout-tip
## RStudio on cloud
[https://aic.ufal.mff.cuni.cz/jlab/](https://aic.ufal.mff.cuni.cz/jlab/)
:::
::: callout-tip
## Learning materials on github
[https://github.com/ufal/R_BEGINNERS_SHORT](https://github.com/ufal/R_BEGINNERS_SHORT)
:::
::: callout-tip
## This course in the course catalogue
[https://is.cuni.cz/studium/eng/predmety/index.php?do=predmet&kod=NPFL146](https://is.cuni.cz/studium/eng/predmety/index.php?do=predmet&kod=NPFL146)
:::
::: callout-tip
## DataCamp
[https://www.datacamp.com/users/sign_in](https://www.datacamp.com/users/sign_in)
:::

## Core R
- descriptive statistics

```{r}
observations <- runif(n = 1000, min = 0, max = 1)
summary(observations)
```
```{r}
plot(observations)
```



##



- statistical modeling
- visualization (plots)




::: note
Data science: making sense of data. around statistics & visualization. 
:::




























